/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ConnectDB;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author phamk
 */
public class DangNhap extends javax.swing.JFrame {
 ConnectDB db=new ConnectDB();
    Connection conn=db.getConnection();
         PreparedStatement pst =null;
    ResultSet rs =null;
    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        setTitle("Đăng nhập hệ thống");
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(java.awt.Color.lightGray); //Set màu cho background giao diện
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TaiKhoan = new javax.swing.JTextField();
        MatKhau = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bá.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Phần mềm quản lý mua bán oto");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-login-100.png"))); // NOI18N

        jLabel4.setText("Tên đăng nhập");

        jLabel5.setText("Mật khẩu");

        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(141, 141, 141))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TaiKhoan)
                            .addComponent(MatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Tạo biến id gắn giá trị null    
    String id=null;
        //hàm lấy mã nhân viên qua usename
        public String Use(String u){
        String Get="Select MaNV from NhanVien where UseName=?";
        try{
            //truy vấn cơ sở dữ liệu
        pst=conn.prepareStatement(Get);
        pst.setString(1, u);
        rs=pst.executeQuery();
        //next() trả về một giá trị boolean, true nếu còn dòng dữ liệu tiếp theo trong tập kết quả và
        //con trỏ đã được di chuyển đến dòng đó, false nếu không còn dòng dữ liệu 
        //nào và con trỏ đã di chuyển qua dòng cuối cùng.
        if(rs.next()){
            id=rs.getString("MaNV");
        }
            System.out.println(id);
        }catch(Exception ex){
            
        }
        return id;
    }
        int cv=0;
        String tk,mk=null;
        public int TaiKhoan(String u,String p){
        String Get="Select ChucVu from Account where UseName=? and Pass=?";
        try{
        pst=conn.prepareStatement(Get);
        pst.setString(1, u);
        pst.setString(2, p);
        //executeQuery() được sử dụng khi bạn muốn thực thi một truy vấn SQL trả về dữ liệu
        rs=pst.executeQuery();
        if(rs.next()){
            cv=rs.getInt("ChucVu");
        }
        }catch(Exception ex){
            
        }
        return cv;
    }
         public static String getMd5(String input) 
    { 
        try { 
           // Phương thức getInstance tĩnh được gọi với hàm băm MD5
            MessageDigest md = MessageDigest.getInstance("MD5"); 
  
         // phương thức digest() được gọi để tính toán thông báo tóm tắt
            // của một đầu vào digest() trả về mảng byte
            byte[] messageDigest = md.digest(input.getBytes()); 
  
            // Chuyển đổi mảng byte thành biểu diễn signum
            BigInteger no = new BigInteger(1, messageDigest); 
  
           // Chuyển đổi thông báo tóm tắt thành giá trị hex
            String hashtext = no.toString(16); 
            while (hashtext.length() < 32) { 
                hashtext = "0" + hashtext; 
            } 
            return hashtext; 
        }  
        // Để chỉ định các thuật toán phân loại thông báo sai 
        // Để chỉ định các thuật toán phân loại thông báo sai
        catch (NoSuchAlgorithmException e) { 
            throw new RuntimeException(e); 
        } 
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
           //Kiểm tra text xem rỗng không
         if(TaiKhoan.getText().equals("")||MatKhau.getText().equals(""))
         {
             JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
         }else{
             String sql="Select * from Account Where UseName=? and Pass=?";
         PreparedStatement pst= conn.prepareCall(sql);
         pst.setString(1, TaiKhoan.getText());
         pst.setString(2, getMd5(MatKhau.getText()));
         ResultSet rs=pst.executeQuery();
         if(rs.next()){
            System.out.println("ChucVU"+TaiKhoan(TaiKhoan.getText(),getMd5(MatKhau.getText())));
            System.out.println(Use(TaiKhoan.getText()));
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
           if(cv==0){
                AdminHome ftc=new AdminHome();
                ftc.setVisible(true);
                ftc.setLocationRelativeTo(null);
                this.dispose();
           }else{
               //hàm khởi tạo có tham số id nhân viên 
               TrangChu tcnv=new TrangChu(id);
                tcnv.setVisible(true);
                tcnv.setLocationRelativeTo(null);
                this.dispose();
           }
             
         }else{
             JOptionPane.showMessageDialog(this, "Tài khoản mật khảu không chính xác");
         }
         }
          }catch(SQLException ex){
              JOptionPane.showMessageDialog(this, ex.toString());
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MatKhau;
    private javax.swing.JTextField TaiKhoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
