/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ConnectDB;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamk
 */
public class FomSuaXe extends javax.swing.JFrame {
byte[] photo=null;
String fileName=null;
private ImageIcon format=null;
   ConnectDB db=new ConnectDB();
    Connection conn=db.getConnection();
    PreparedStatement pst =null;
    ResultSet rs =null;
    DefaultTableModel model=null;
    /**
     * Creates new form FomSuaXe
     */
    private String id=null;
    public FomSuaXe(String IDXe) {
        setTitle("Form sửa thông tin xe");
        initComponents();
                setLocationRelativeTo(null);
        LoadCBHangXe();
        this.id=IDXe;
        JOptionPane.showMessageDialog(this, id);
              try{
        String get="SELECT        dbo.Xe.MaXe, dbo.Xe.TenXe, dbo.Xe.HinhAnh, dbo.HangSanXuat.TenHSX, dbo.Xe.Gia, dbo.Xe.TrangThai\n" +
"FROM            dbo.HangSanXuat INNER JOIN\n" +
"                         dbo.Xe ON dbo.HangSanXuat.MaHSX = dbo.Xe.MaHSX where Xe.MaXe=?";
        pst=conn.prepareStatement(get);
        pst.setString(1, id);
        rs=pst.executeQuery();
        if (rs.next()) {
        txtTenXe.setText(rs.getString(2));
        byte[] imageBytes = rs.getBytes(3);
        ImageIcon imageIcon = new ImageIcon(imageBytes);
        txtHinhAnh.setIcon(imageIcon);
        CbHangSanXuat.setSelectedItem(rs.getString(4));
        txtGiaBan.setText(rs.getString(5));
         if(rs.getInt(6)==0){
        CbTrangThai.setSelectedItem("Mới");
                }else{
        CbTrangThai.setSelectedItem("Đã qua sử dụng");
                }
        

}
         }catch(Exception ex){
             System.out.println(ex.toString());
         }
    }

    FomSuaXe() {
    }
    public void Load(){
         try{
        String get="SELECT        dbo.Xe.MaXe, dbo.Xe.TenXe, dbo.Xe.HinhAnh, dbo.HangSanXuat.TenHSX, dbo.Xe.Gia, dbo.Xe.TrangThai\n" +
"FROM            dbo.HangSanXuat INNER JOIN\n" +
"                         dbo.Xe ON dbo.HangSanXuat.MaHSX = dbo.Xe.MaHSX where Xe.MaXe=?";
        pst=conn.prepareStatement(get);
        pst.setString(1, id);
        rs=pst.executeQuery();
        if (rs.next()) {
        txtTenXe.setText(rs.getString(2));
        byte[] imageBytes = rs.getBytes(3);
        ImageIcon imageIcon = new ImageIcon(imageBytes);
        txtHinhAnh.setIcon(imageIcon);
        CbHangSanXuat.setSelectedItem(rs.getString(4));
        txtGiaBan.setText(rs.getString(5));
         if(rs.getInt(6)==0){
        CbTrangThai.setSelectedItem("Mới");
                }else{
        CbTrangThai.setSelectedItem("Đã qua sử dụng");
                }
        

}
         }catch(Exception ex){
             System.out.println(ex.toString());
         }
    }
    
    
    
    
    
    
 public void LoadCBHangXe(){
             try{
                CbHangSanXuat.removeAllItems();
                String get="Select TenHSX from HangSanXuat";
                pst=conn.prepareStatement(get);
                rs=pst.executeQuery();
                while(rs.next()){
                    String name=rs.getString("TenHSX");
                CbHangSanXuat.addItem(name);
                }
        }   catch(Exception ex) {
             System.out.println(ex.toString());
        }
    }
    
    String mh=null;
    public String mahsx(){
          String tmp=(String)CbHangSanXuat.getSelectedItem().toString();
        String GetMaLoai="Select * from HangSanXuat where TenHSX=?";
        try{
        pst=conn.prepareStatement(GetMaLoai);
        pst.setString(1, tmp);
        rs=pst.executeQuery();
        if(rs.next()){
            mh=rs.getString("MaHSX");
        }
        }catch(Exception ex){
            
        }
        return mh;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHinhAnh = new javax.swing.JLabel();
        btnUpLoad = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CbHangSanXuat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CbTrangThai = new javax.swing.JComboBox<>();
        txtGiaBan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHinhAnh.setText("Hình ảnh");
        txtHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUpLoad.setText("Tải ảnh");
        btnUpLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpLoadActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel2.setText("Hãng sản xuất");

        CbHangSanXuat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbHangSanXuat.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CbHangSanXuatPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel1.setText("Tên xe");

        jLabel4.setText("Trạng thái");

        CbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Đã qua sử dụng", " " }));

        jLabel3.setText("Giá bán");

        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnUpLoad)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLuu)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenXe)
                                    .addComponent(CbHangSanXuat, 0, 130, Short.MAX_VALUE))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(25, 25, 25)
                                        .addComponent(CbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(CbHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnUpLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(jButton1))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpLoadActionPerformed
        // TODO add your handling code here:
        //Hiện thị ảnh
        JFileChooser choose=new JFileChooser();
        choose.showOpenDialog(null);
        File f=choose.getSelectedFile();
        txtHinhAnh.setIcon(new ImageIcon(f.toString()));
        fileName=f.getAbsolutePath();
        ImageIcon ii = new ImageIcon(fileName);
        //            Resize image to fit jlabel
        Image images = ii.getImage().getScaledInstance(txtHinhAnh.getWidth(), txtHinhAnh.getHeight(), Image.SCALE_SMOOTH);

        txtHinhAnh.setIcon(new ImageIcon(images));
        try{
            File image=new File(fileName);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf= new byte[1024];

            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            photo=bos.toByteArray();
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUpLoadActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
            try{
            String get="UPDATE Xe SET TenXe=?,HinhAnh=?,MaHSX=?,Gia=?,TrangThai=? WHERE MaXe=?";
             pst=conn.prepareStatement(get);
                pst.setString(6,id);
                pst.setString(1,txtTenXe.getText());
                if(photo==null){
                    String text = txtHinhAnh.getText();
                     byte[] imageBytes = text.getBytes();
                     //byte[] imageBytes = rs.getBytes(3);File imageFile = new File("path/to/image.jpg");

                     
                    pst.setBytes(2,imageBytes);
                }else{
                    pst.setBytes(2,photo);
                }
                pst.setString(3,mh);
                pst.setString(4,txtGiaBan.getText());
                if(CbTrangThai.getSelectedItem()=="Mới"){
                    pst.setInt(5, 0);
                }
                if(CbTrangThai.getSelectedItem()=="Đã qua sử dụng"){
                    pst.setInt(5, 1);
                }
                if(pst.executeUpdate()==1){
                    JOptionPane.showMessageDialog(this, "Sửa thông tin thành công");
                }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void CbHangSanXuatPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CbHangSanXuatPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        mahsx();
        JOptionPane.showMessageDialog(this, mahsx());
    }//GEN-LAST:event_CbHangSanXuatPopupMenuWillBecomeInvisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FomSuaXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FomSuaXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FomSuaXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FomSuaXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FomSuaXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbHangSanXuat;
    private javax.swing.JComboBox<String> CbTrangThai;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnUpLoad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JLabel txtHinhAnh;
    private javax.swing.JTextField txtTenXe;
    // End of variables declaration//GEN-END:variables
}
