/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.ConnectDB;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamk
 */
public class QuanLy extends javax.swing.JPanel {
    ConnectDB db=new ConnectDB();
    Connection conn=db.getConnection();
    PreparedStatement pst =null;
    ResultSet rs =null;
    DefaultTableModel model=null;
    byte[] photo=null;
String fileName=null;
private ImageIcon format=null;
    /**
     * Creates new form QuanLy
     */
    public QuanLy() {
        initComponents();
        LockForm();
        txtMa.setEnabled(false);
        loadtable();
        loadtable2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenHang = new javax.swing.JTextField();
        txtXuatXu = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        btnThem2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtHinhAnh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1050, 600));
        setPreferredSize(new java.awt.Dimension(1050, 600));

        jLabel1.setText("Thông tin hãng sản xuất");

        jLabel2.setText("Tên hãng sản xuất");

        jLabel3.setText("Xuất xứ");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ", "Hãng sản xuất", "Xuất xứ"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtXuatXu)
                            .addComponent(txtTenHang)
                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnLuu))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSua)
                                .addGap(39, 39, 39)
                                .addComponent(btnXoa))
                            .addComponent(btnHuy))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Thông tin xe");

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ", "Xe", "Hình ảnh", "Hãng sản xuất", "Giá", "Trạng thái"
            }
        ));
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table2);

        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHinhAnh.setText("Hình ảnh");
        txtHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThem2)
                                .addGap(124, 124, 124))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(107, 107, 107)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGap(76, 76, 76))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1))
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem2)
                            .addComponent(jButton2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Thông tin hãng sản xuất");
    }// </editor-fold>//GEN-END:initComponents
 private void UnLockForm()
    {
        txtTenHang.setEnabled(true);
        txtXuatXu.setEnabled(true);
        
        btnThem.setEnabled(false);
        //btnSua.setEnabled(false);
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }
   private void LockForm()
    {
        txtTenHang.setEnabled(false);
        txtXuatXu.setEnabled(false);
        btnThem.setEnabled(true);
        //btnSua.setEnabled(true);
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);
    }
      public boolean Check(){
   if( txtTenHang.getText().isEmpty()||
    txtXuatXu.getText().isEmpty()){
    return true;
}
            return false;
}
      public void loadtable(){
         try{
        String get="SELECT * FROM HangSanXuat";
        pst=conn.prepareStatement(get);
        rs=pst.executeQuery();
        ResultSetMetaData stData=rs.getMetaData();
        int kq=stData.getColumnCount();
        DefaultTableModel RecordTable= (DefaultTableModel)Table1.getModel();
        RecordTable.setRowCount(0);
        while(rs.next()){
            Vector columnData=new Vector();
            for(int i=0;i<=kq;i++){
                columnData.add(rs.getString(1));
                columnData.add(rs.getString(2));
                columnData.add(rs.getString(3));

            }
            RecordTable.addRow(columnData);
         }
         }catch(Exception ex){
             System.out.println(ex.toString());
         }
    }
       public void loadtable2(){
         try{
        String get="SELECT        dbo.Xe.MaXe, dbo.Xe.TenXe, dbo.Xe.HinhAnh, dbo.HangSanXuat.TenHSX, dbo.Xe.Gia, dbo.Xe.TrangThai\n" +
"FROM            dbo.HangSanXuat INNER JOIN\n" +
"                         dbo.Xe ON dbo.HangSanXuat.MaHSX = dbo.Xe.MaHSX";
        pst=conn.prepareStatement(get);
        rs=pst.executeQuery();
        ResultSetMetaData stData=rs.getMetaData();
        int kq=stData.getColumnCount();
        DefaultTableModel RecordTable= (DefaultTableModel)Table2.getModel();
        RecordTable.setRowCount(0);
        while(rs.next()){
            Vector columnData=new Vector();
            for(int i=0;i<=kq;i++){
                columnData.add(rs.getString(1));
                columnData.add(rs.getString(2));
                byte[] image=rs.getBytes(3);
                columnData.add(image);
                columnData.add(rs.getString(4));
                columnData.add(rs.getString(5));
                 if(rs.getInt(6)==0){
                columnData.add("Mới");
                }else{
                columnData.add("Đã qua sử dụng");

                }

            }
            RecordTable.addRow(columnData);
         }
         }catch(Exception ex){
             System.out.println(ex.toString());
         }
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        UnLockForm();
        loadtable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        LockForm();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(!Check()){
            try{
            String get="INSERT INTO HangSanXuat VALUES(?,?)";
                pst=conn.prepareStatement(get);
                pst.setString(1,txtTenHang.getText());
                pst.setString(2,txtXuatXu.getText());
                if(pst.executeUpdate()==1){
                    JOptionPane.showMessageDialog(this, "Lưu thông tin thành công");
                   loadtable();
                   txtTenHang.setText("");
                   txtXuatXu.setText("");
                }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
    }
       }else{
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đây đủ thông tin");
       }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
         model=(DefaultTableModel)Table1.getModel();
        int c=Table1.getSelectedRow();
        txtMa.setText(model.getValueAt(c, 0).toString());
        txtTenHang.setText(model.getValueAt(c, 1).toString());
        txtXuatXu.setText(model.getValueAt(c, 2).toString());
    }//GEN-LAST:event_Table1MouseClicked

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        // TODO add your handling code here:
         FomThemXe tcnv=new FomThemXe();
                tcnv.setVisible(true);
                tcnv.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadtable2();
        //txtHinhAnh.setText("");
       String filePath = txtHinhAnh.getText();
        File file = new File(filePath);
        if (file.exists()) {
            file.delete();
        }
        txtHinhAnh.setText("");
        fileName=null;
        photo=null;
        txtHinhAnh.setIcon(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
        // TODO add your handling code here:
         model=(DefaultTableModel)Table2.getModel();
        int c=Table2.getSelectedRow();
        byte[] image=(byte[]) model.getValueAt(c, 2);
        ImageIcon ii = new ImageIcon(image);
        Image images = ii.getImage().getScaledInstance(txtHinhAnh.getWidth(), txtHinhAnh.getHeight(), Image.SCALE_SMOOTH);
        format=new ImageIcon(images);
        txtHinhAnh.setIcon(format);
    }//GEN-LAST:event_Table2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          model=(DefaultTableModel)Table2.getModel();
        int c=Table2.getSelectedRow();
        String IDXe = model.getValueAt(c, 0).toString();  
       if(model==null){
        JOptionPane.showMessageDialog(this, "Bạn chưa chọn thông tin");
       }else{
            Component rootPane=null;
          int check_log_out = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn sửa thông tin xe này?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (check_log_out == JOptionPane.YES_OPTION) {
                    new FomSuaXe(IDXe).setVisible(true);
        } 
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        model=(DefaultTableModel)Table2.getModel();
        int c=Table2.getSelectedRow();
        Component rootPane=null;
          int check_log_out = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa thông xe này?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (check_log_out == JOptionPane.YES_OPTION) {
                  String IDXe = model.getValueAt(c, 0).toString();
         try{
            String get="DELETE FROM Xe where MaXe=?";
              pst=conn.prepareStatement(get);
                pst.setString(1,IDXe);
                pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadtable2();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        } 
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
         try{
            String get="UPDATE HangSanXuat SET TenHSX=?,XuatXu=? WHERE MaHSX=?";
             pst=conn.prepareStatement(get);
                pst.setString(3,txtMa.getText());
                pst.setString(1,txtTenHang.getText());
                pst.setString(2,txtXuatXu.getText());
                if(pst.executeUpdate()==1){
                    JOptionPane.showMessageDialog(this, "Sửa thông tin thành công");
                        loadtable();
                         txtTenHang.setText("");
                   txtXuatXu.setText("");
                   txtMa.setText("");
                }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         // Xóa
         try{
            String get="DELETE FROM HangSanXuat where MaHSX=?";
              pst=conn.prepareStatement(get);
                pst.setString(1,txtMa.getText());
                pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                        loadtable();
                         txtTenHang.setText("");
                   txtXuatXu.setText("");
                   txtMa.setText("");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtHinhAnh;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTenHang;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
