/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.ConnectDB;
import java.awt.Component;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamk
 */
public class QuanLyNhanVien extends javax.swing.JPanel {
    ConnectDB db=new ConnectDB();
    Connection conn=db.getConnection();
    PreparedStatement pst =null;
    ResultSet rs =null;
    DefaultTableModel model=null;
    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        LockForm();
        txtMaNhanVien.setEnabled(false);
        loadtable();
    }
 private void UnLockForm()
    {
        txtTenNhanVien.setEnabled(true);
        txtDiaChi.setEnabled(true);
        txtSdt.setEnabled(true);
        radioNam.setEnabled(true);
        radioNu.setEnabled(true);
        CbChucVu.setEnabled(true);

        btnThem1.setEnabled(false);
        btnLuu1.setEnabled(true);
        btnHuy1.setEnabled(true);
    }
   private void LockForm()
    {
       txtTenNhanVien.setEnabled(false);
        txtDiaChi.setEnabled(false);
        txtSdt.setEnabled(false);
        radioNam.setEnabled(false);
        radioNu.setEnabled(false);
        CbChucVu.setEnabled(false);
        
        btnThem1.setEnabled(true);
        btnLuu1.setEnabled(false);
        btnHuy1.setEnabled(false);
    }
    public boolean Check(){
    if( txtTenNhanVien.getText().isEmpty()||
    txtDiaChi.getText().isEmpty()||
    txtSdt.getText().isEmpty())
    {
    return true;
    }
        return false;
    }
      //Làm mới text
     public void reset(){
         txtMaNhanVien.setText("");
        radioNam.setSelected(false);     
        radioNu.setSelected(false);
        txtDiaChi.setText("");
        txtSdt.setText("");
        txtTenNhanVien.setText("");
     }
//     Table là một đối tượng JTable.
//getModel() là một phương thức của đối tượng JTable để truy xuất mô hình dữ liệu của bảng.
//(DefaultTableModel) là việc ép kiểu (casting) để chuyển đổi mô hình dữ liệu của JTable thành kiểu DefaultTableModel.
//RecordTable là biến kiểu DefaultTableModel để lưu trữ mô hình dữ liệu của JTable.
//Sau khi thực hiện đoạn mã trên, RecordTable sẽ trỏ đến cùng một đối tượng mô hình dữ liệu
//        (model) mà Table đang sử dụng. Điều này cho phép bạn thao tác với dữ liệu trong JTable
//        thông qua biến RecordTable, như thêm, xóa hoặc cập nhật các dòng dữ liệu trong bảng.
      public void loadtable(){
         try{
        String get="SELECT * FROM NhanVien";
        //String get="SELECT * FROM NhanVien";
        pst=conn.prepareStatement(get);
        rs=pst.executeQuery();
        ResultSetMetaData stData=rs.getMetaData();
        int kq=stData.getColumnCount();
        DefaultTableModel RecordTable= (DefaultTableModel)Table.getModel();
        RecordTable.setRowCount(0);
        while(rs.next()){
            Vector columnData=new Vector();
            for(int i=0;i<=kq;i++){
                columnData.add(rs.getString(1));
                columnData.add(rs.getString(2));
                if(rs.getInt(3)==0){
                columnData.add("Nam");
                }else{
                columnData.add("Nữ");

                }
                columnData.add(rs.getString(4));
                columnData.add(rs.getString(5));
                 if(rs.getInt(6)==0){
                columnData.add("Quản lý");
                }else{
                columnData.add("Nhân viên");
                //id=rs.getString(9);
                }
            }
            RecordTable.addRow(columnData);
         }
         }catch(Exception ex){
             System.out.println(ex.toString());
         }
    }
      String id=null;
        public String Use(int MaNV){
        String Get="Select UseName from NhanVien where MaNV=?";
        try{
        pst=conn.prepareStatement(Get);
        pst.setInt(1, MaNV);
        rs=pst.executeQuery();
        if(rs.next()){
            id=rs.getString("UseName");
        }
            System.out.println(id);
        }catch(Exception ex){
            
        }
        return id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnThem1 = new javax.swing.JButton();
        btnLuu1 = new javax.swing.JButton();
        btnHuy1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        CbChucVu = new javax.swing.JComboBox<>();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        btnTaoTaiKhoan = new javax.swing.JButton();

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Nhân viên", "Giới tính", "Địa chỉ", "Số điện thoại", "Chức vụ"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin nhân sự");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnLuu1.setText("Lưu");
        btnLuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu1ActionPerformed(evt);
            }
        });

        btnHuy1.setText("Hủy");
        btnHuy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuy1ActionPerformed(evt);
            }
        });

        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhân viên");

        jLabel3.setText("Giới tính");

        jLabel4.setText("Địa chỉ");

        jLabel5.setText("Số điện thoại");

        jLabel6.setText("Chức vụ");

        jLabel7.setText("Mã nhân viên");

        CbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lý", " ", " " }));

        buttonGroup1.add(radioNam);
        radioNam.setText("Nam");

        buttonGroup1.add(radioNu);
        radioNu.setText("Nữ");

        btnTaoTaiKhoan.setText("Tạo tài khoản");
        btnTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem1)
                            .addComponent(btnLuu1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CbChucVu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(radioNam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioNu))
                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua1)
                            .addComponent(btnHuy1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTaoTaiKhoan)
                            .addComponent(btnXoa1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(radioNam)
                            .addComponent(radioNu))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem1)
                            .addComponent(btnSua1)
                            .addComponent(btnXoa1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuu1)
                            .addComponent(btnHuy1)
                            .addComponent(btnTaoTaiKhoan))
                        .addGap(73, 73, 73))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        UnLockForm();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        LockForm();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try{
           
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // Xóa
        try{
          
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        UnLockForm();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnLuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu1ActionPerformed
        // TODO add your handling code here:
         if(!Check()){
        try{
            String get="INSERT INTO NhanVien(TenNV,GioiTinh,DiaChi,Sdt,ChucVu) VALUES(?,?,?,?,?)";
                pst=conn.prepareStatement(get);
                pst.setString(1,txtTenNhanVien.getText());
                if(radioNam.isSelected()){
                    pst.setInt(2, 0);
                }
                if(radioNu.isSelected()){
                    pst.setInt(2, 1);
                }
                pst.setString(3,txtDiaChi.getText());
                pst.setString(4,txtSdt.getText());
                if(CbChucVu.getSelectedItem()=="Nhân viên"){
                    pst.setInt(5, 0);
                }
                if(CbChucVu.getSelectedItem()=="Quản lý"){
                    pst.setInt(5, 1);
                }
                if(pst.executeUpdate()==1){
                    JOptionPane.showMessageDialog(this, "Thêm thông tin thành công");
                    reset();
                    loadtable();
                }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
    }
        }else{
           JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin đầy đủ");

        }
    }//GEN-LAST:event_btnLuu1ActionPerformed

    private void btnHuy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuy1ActionPerformed
        // TODO add your handling code here:
        LockForm();
    }//GEN-LAST:event_btnHuy1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        //setString là một phương thức trong đối tượng PreparedStatement
        try{
           String get="UPDATE NhanVien SET TenNV=?,GioiTinh=?,DiaChi=?,Sdt=?,ChucVu=? WHERE MaNV=?";
             pst=conn.prepareStatement(get);
            pst.setString(6,txtMaNhanVien.getText());
            pst.setString(1,txtTenNhanVien.getText());
                if(radioNam.isSelected()){
                    pst.setInt(2, 0);
                }
                if(radioNu.isSelected()){
                    pst.setInt(2, 1);
                }
                pst.setString(3,txtDiaChi.getText());
                pst.setString(4,txtSdt.getText());
                if(CbChucVu.getSelectedItem()=="Nhân viên"){
                    pst.setInt(5, 0);
                }
                if(CbChucVu.getSelectedItem()=="Quản lý"){
                    pst.setInt(5, 1);
                }
                if(pst.executeUpdate()==1){
                    JOptionPane.showMessageDialog(this, "Sửa thông tin thành công");
                    reset();
                    loadtable();
                }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // Xóa
        try{
            String get="DELETE FROM NhanVien where MaNV=?";
              pst=conn.prepareStatement(get);
                pst.setString(1,txtMaNhanVien.getText());
                pst.executeUpdate();
            String get1="DELETE FROM Account where UseName=?";
              pst=conn.prepareStatement(get1);
                pst.setString(1,id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                reset();
                loadtable();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        //có chức năng để lấy mô hình dữ liệu (model) 
        //của một đối tượng JTable và gán cho một biến kiểu DefaultTableModel.
         model=(DefaultTableModel)Table.getModel();
        int c=Table.getSelectedRow();
        txtMaNhanVien.setText(model.getValueAt(c, 0).toString());
        txtTenNhanVien.setText(model.getValueAt(c, 1).toString());
        String sex=model.getValueAt(c, 2).toString();
        if(sex.equals("Nam")){
            radioNam.setSelected(true);
        }
        if(sex.equals("Nữ")){
            radioNu.setSelected(true);
        }        
      
        txtDiaChi.setText(model.getValueAt(c, 3).toString());
        txtSdt.setText(model.getValueAt(c, 4).toString());
        String cv=model.getValueAt(c, 5).toString();
        if(cv.equals("Quản lý")){
            CbChucVu.setSelectedItem("Quản lý");
        }else{
            CbChucVu.setSelectedItem("Nhân viên");
        }
         int i = Integer.parseInt(txtMaNhanVien.getText());
        Use(i);
    }//GEN-LAST:event_TableMouseClicked

    private void btnTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanActionPerformed
        // TODO add your handling code here:
          model=(DefaultTableModel)Table.getModel();
        int c=Table.getSelectedRow();
        String MaNV =(model.getValueAt(c, 0).toString());
        int i = Integer.parseInt(MaNV);
        Use(i);
         Component rootPane=null;
          int check_log_out = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn tạo tài khoản đăng nhập cho nhân viên này không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(Use(i)==null){
             if (check_log_out == JOptionPane.YES_OPTION) {
                    new TaiKhoan(MaNV).setVisible(true);
        } 
        }else{
                      JOptionPane.showMessageDialog(this, "Nhân viên đâ có tài khoản");
 
        }
    }//GEN-LAST:event_btnTaoTaiKhoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbChucVu;
    private javax.swing.JTable Table;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnHuy1;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuu1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnTaoTaiKhoan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
